/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#define SHCRS 	*(uint32_t*)0xE000ED24
#define CFSR 	*(uint32_t*)0xE000ED28

#define FAULT_USAGE 18
#define FAULT_BUS 17
#define FAULT_MEM_MANAGE 16
#define FAULT_SVCALL_PENDED 15
#define FAULT_SVCALL_ACTIVE 7

//#define UNDEF_1
//#define UNDEF_2
//#define DIV0
#define PERI

enum UsageFaultType{
	UNDEFINSTR 	= 0x1,
	INVSTATE	= 0x2,
	INVPC		= 0x4,
	NOCP		= 0x8,
	UNALIGNED	= 0x100,
	DIVBYZERO	= 0x200
};

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

enum UsageFaultType check_usage_fault(void) {
	enum UsageFaultType ret = CFSR >> 16;
	return ret;
}


int main(void)
{
    /* Loop forever */
	printf("Bodo!\n");

	SHCRS |= (1 << FAULT_USAGE); 		//Enable Usage Fault
	SHCRS |= (1 << FAULT_MEM_MANAGE);	//Enable Mem Fault
	SHCRS |= (1 << FAULT_BUS);			//Enable Bus Fault

	/* 1- Undefined Instruction */
#ifdef UNDEF_1
	/* Method 1 */
	uint32_t *pINV = (uint32_t*) 0x2000FF01; //Needs to finish to 1 due the T bit
	*pINV = 0xFFFFFFFF;

	void (*function_pointer)(void);
	function_pointer = (void*) pINV;

	function_pointer();
#endif

#ifdef UNDEF_2
	/* Method 2 */
	__asm volatile("LDR R3, =#0x2000FF01");
	__asm volatile("BLX R3");
#endif

	/* 2- Divide by zero */
#ifdef DIV0

	int res = 10/0;

#endif


#ifdef PERI
	/* 3- Instruction from peripheral region */
	//pointer to peripheral region
	uint32_t *pPERI = (uint32_t*) 0x5000FFFF;
	//*pPER = 0x12345678;
	//Create function pointer and point it to pPER
	void (*crazy_func)(void);
	crazy_func = pPERI;

	//Call function
	crazy_func();
#endif



	/* 4- Executing SVC inside the SVC handler*/
	/* 5- Executing SVC instruction inside interrupt handler*/


	for(;;);
}


void MemManage_Handler(void){
	printf("Pacu: \n");
}

void BusFault_Handler(void){

}

void UsageFault_Handler(void){
	printf("Jaraqui: \n");

    switch(check_usage_fault()){
    case UNDEFINSTR:
    	printf("psicodelico\n");
    	break;
    case INVSTATE:
    	printf("auspicioso\n");
    	break;
    case DIVBYZERO:
    	printf("inefavel\n");
    	break;
    default:
    	printf("enfadoinho\n");
    }
}
