/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define EX6

int main(void)
{
#ifdef EX1
	/*(1) Load two register, add them and store the result in memory  */
	__asm volatile("LDR R3,=#0x20001000");
	__asm volatile("LDR R4,=#0x20001004");
	__asm volatile("LDR R5,=#0x20001008");
	__asm volatile("LDR R1,[R3]");
	__asm volatile("LDR R2,[R4]");
	__asm volatile("ADD R0,R1,R2");
	__asm volatile("STR R0,[R5]");
#endif


#ifdef EX2
	/*(2) Move the content of a C variable to R0 register*/
	uint8_t var = 9;
	__asm volatile("MOV R0,%0": :"r"(var));
#endif

#ifdef EX3
	/*(3) Move the content of CONTROLE register to a C variable*/
	uint32_t var;
	__asm volatile("MRS %0,CONTROL" : "=r"(var));
#endif

#ifdef EX4
	/*(4) Copy the content of a variable to another*/
	uint32_t var1 = 10, var2 = 2;
	__asm volatile("MOV %0,%1" : "=r"(var1) : "r"(var2));
#endif

#ifdef EX5
	/*(5) Copy a content of a pointer to another variable*/
	uint32_t *p;
	p = 0x20001000;
	*p = 10;

	uint32_t var;

	__asm volatile("LDR %0, [%1]" : "=r"(var) : "r"(p));
#endif

#ifdef EX6
	/*(6) Move a register with a value*/
	__asm volatile("MOV R2,%0" : : "i"(80));
	__asm volatile("MOV R1,%0" : : "r"(0x50));
#endif

    /* Loop forever */
	for(;;);
}
