/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define ISER_NUM_BITS 32
#define ISPR_NUM_BITS 32
#define EXTI0_IRQ_NUMBER 6
#define SPI4_IRQ_NUMBER 84

void enable_exception(const uint8_t irq_number) {
	//NVIC_ISERx base address
	volatile uint32_t *const pISER_base = (uint32_t*) 0xE000E100;
	//Calculate which ISER to use
	volatile uint32_t *const pISER = (uint32_t*) pISER_base + (irq_number / ISER_NUM_BITS);

	//Set IRQ bit
	*pISER |= (1 << (irq_number%ISER_NUM_BITS));
}

void set_pending(const uint8_t irq_number) {
	//NVIC ISPRx base address
	volatile uint32_t *const pISPR_base = (uint32_t*) 0xE000E200;
	//Calculate which ISPR to use
	volatile uint32_t *const pISPR = (uint32_t*) pISPR_base + (irq_number / ISPR_NUM_BITS);

	//Set IRQ bit
	*pISPR |= (1 << (irq_number%ISPR_NUM_BITS));
}

int main(void)
{
    /* Loop forever */
	printf("Jaraqui!\n");

	/* EXT0 IRQ number 6 */
	enable_exception(EXTI0_IRQ_NUMBER);

	/* Set EXTI0 as pending */
	set_pending(EXTI0_IRQ_NUMBER);

	/* EXT0 IRQ number 6 */
	enable_exception(SPI4_IRQ_NUMBER);

	/* Set EXTI0 as pending */
	set_pending(SPI4_IRQ_NUMBER);


	for(;;);
}


void EXTI0_IRQHandler() {
	printf("Pacuzinho\n");
}

void SPI4_IRQHandler() {
	printf("Matrinxa\n");
}
