/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define STACK_START 0x20000400
#define MSP_END		0x20000200
#define PSP_END		0x20000000

int func(int a, int b, int c, int d) {
	return a+b+c+d;
}

__attribute__((naked)) void change_stack() {
    /* Loop forever */
	uint32_t ret_control = 0;

	/* Change stack to PSP in Thread Mode  */
	/* 1- Load a valid memory address into PSP */
	__asm volatile("MOV R0,%0" : : "r"(MSP_END)); //move PSP address to R0
	__asm volatile("MSR PSP,R0"); //Set PSP address

	/* 2- Load a valid memory address into MSP */
	__asm volatile("MOV R0,%0" : : "r"(STACK_START)); //move PSP address to R0
	__asm volatile("MSR MSP,R0"); //Set PSP address

	/* 3- Set the SPSEL bit on CONTROL register */
	__asm volatile("MRS %0,CONTROL" : "=r"(ret_control)); //read CONTROL register
	ret_control = (1 << 1);
	__asm volatile("MSR CONTROL,%0" : : "r"(ret_control)); //Write CONTROL register

	__asm volatile("BX LR");
}

int main(void)
{
	change_stack();

	int ret = 0;
	ret = func(1,5,3,1);

	printf("Ret values is %d", ret);

	for(;;);
}
