/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	__asm volatile("SVC #0x02");
    /* Loop forever */
	for(;;);
}

/* to avoid to get the stack already modified by the
 * function prologue it should be used the naked function
*/
__attribute__((naked)) void SVC_Handler(void) {
	__asm volatile("MRS R0,MSP");
	//Call function SVC_Handler_c and pass the argument through R0
	__asm volatile("B SVC_Handler_c");
}

void SVC_Handler_c(uint32_t* msp) {
	//Retrive MSP stack value
	//uint32_t msp;
	//__asm volatile("MRS %0,MSP" : "=r"(msp));

	//Switch to the PC address on the stack
	//uint32_t *next_ins = msp;
	//next_ins += 12;
	uint32_t *next_ins = msp[6];

	//Get the value of previous instruction which contains the SVC number
	//uint32_t *svc_number_addr = *(next_ins)-2;
	uint8_t *svc_number_addr = (uint8_t*) next_ins-2;
	uint8_t svc_number = *svc_number_addr;
	printf("Jaraquiler!\n");
	printf("SVC Number: %d\n", svc_number);
}
