/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define ISER_NUM_BITS 32
#define ISPR_NUM_BITS 32
#define IPR_IRQ_PER_REQ 4

#define EXTI0_IRQ_NUMBER 6
#define USART6_IRQ_NUMBER 71
#define SPI4_IRQ_NUMBER 84

void set_exception_priority(const uint8_t irq_number, const uint8_t priority) {
	//NVIC IPRx base address
	volatile uint32_t *const pIPR_base = (uint32_t*) 0xE000E400;
	//Calculate which IPR to use
	volatile uint32_t *const pIPR = (uint32_t*) pIPR_base + (irq_number / IPR_IRQ_PER_REQ);

	//Compute IRQ Priority position
	uint8_t pos = (irq_number % IPR_IRQ_PER_REQ) * 8;

	//Set IRQ Priority
	*pIPR |= ((priority << pos) << 4);
}

void enable_exception(const uint8_t irq_number) {
	//NVIC_ISERx base address
	volatile uint32_t *const pISER_base = (uint32_t*) 0xE000E100;
	//Calculate which ISER to use
	volatile uint32_t *const pISER = (uint32_t*) pISER_base + (irq_number / ISER_NUM_BITS);

	//Set IRQ bit
	*pISER |= (1 << (irq_number%ISER_NUM_BITS));
}

void set_pending(const uint8_t *irq_number, uint8_t size) {
	uint32_t ispr_value = 0;

	//NVIC ISPRx base address
	volatile uint32_t *const pISPR_base = (uint32_t*) 0xE000E200;
	//Calculate which ISPR to use
	volatile uint32_t *const pISPR = (uint32_t*) pISPR_base + (irq_number[0] / ISPR_NUM_BITS);

	//Check all values to set
	for(int i=0; i<size; i++) {
		ispr_value |= (1 << (irq_number[i] % ISPR_NUM_BITS));
	}

	//Set IRQ bit
	*pISPR |= ispr_value;
}

int main(void)
{
	uint8_t irqs[2] = {USART6_IRQ_NUMBER, SPI4_IRQ_NUMBER};
	uint8_t size = sizeof(irqs) / sizeof(irqs[0]);

    /* Loop forever */
	printf("Jaraqui!\n");

	/* Set Exception priority */
	set_exception_priority(USART6_IRQ_NUMBER, 4);
	set_exception_priority(SPI4_IRQ_NUMBER, 2);

	/* USART6 IRQ number 6 */
	enable_exception(USART6_IRQ_NUMBER);
	/* EXT0 IRQ number 6 */
	enable_exception(SPI4_IRQ_NUMBER);

	set_pending(irqs, size);

	for(;;);
}


void USART6_IRQHandler() {
	printf("Tambaqui\n");
}

void SPI4_IRQHandler() {
	printf("Matrinxa\n");
}
