/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	/* Modify a content of the memory location 0x2000_0200 using usual method */
	//Set 0x2000_0200 with 0xFF
	__asm volatile("LDR R0,=#0x20000200");
	__asm volatile("LDRB R1,=#0xFF");
	__asm volatile("STRB R1,[R0]");

	//Usual method
	__asm volatile("LDRB R2,[R0]");
	__asm volatile("AND R2,#0x7F");
	__asm volatile("STRB R2,[R0]");

	//Set 0x2000_0200 with 0xFF
	__asm volatile("STRB R1,[R0]");

	//Bit banding
	__asm volatile("LDR R3,=#0x2200401C");
	__asm volatile("LDRB R4,=#0x00");
	__asm volatile("STRB R4,[R3]");


    /* Loop forever */
	for(;;);
}
