/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#define ADD 36
#define SUB 37
#define MUL 38
#define DIV 39

#include <stdio.h>
#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	/* Store this variables on R0 and R1 register to pass to SVC handler*/
	register uint8_t d1 asm ("r1") = 10;
	register uint8_t d2 asm ("r2") = 5;

	//addition
	__asm volatile("SVC #36");
	uint8_t svc_number;
	__asm volatile("MOV %0,R0" : "=r"(svc_number));
	printf("Tambaquiler! Add: %d\n", svc_number);

	//subtraction
	d1 = 10;
	d2 = 5;
	__asm volatile("SVC #37");
	__asm volatile("MOV %0,R0" : "=r"(svc_number));
	printf("Tambaquiler! Sub: %d\n", svc_number);

	//multiplication
	d1 = 10;
	d2 = 5;
	__asm volatile("SVC #38");
	__asm volatile("MOV %0,R0" : "=r"(svc_number));
	printf("Tambaquiler! Mul: %d\n", svc_number);

	//division
	d1 = 10;
	d2 = 5;
	__asm volatile("SVC #39");
	__asm volatile("MOV %0,R0" : "=r"(svc_number));
	printf("Tambaquiler! Div: %d\n", svc_number);

	for(;;);
}

/* to avoid to get the stack already modified by the
 * function prologue it should be used the naked function
*/
__attribute__((naked)) void SVC_Handler(void) {
	__asm volatile("MRS R0,MSP");
	//Call function SVC_Handler_c and pass the argument through R0
	__asm volatile("B SVC_Handler_c");
}

void SVC_Handler_c(uint32_t* msp) {
	//Retrive MSP stack value
	uint32_t *next_ins = msp[6];
	uint8_t arg1 = msp[1];
	uint8_t arg2 = msp[2];

	//Get the value of previous instruction which contains the SVC number
	uint8_t *svc_number_addr = (uint8_t*) next_ins-2;
	uint8_t svc_number = *svc_number_addr;
	printf("Jaraquiler! SVC Number: %d\n", svc_number);

	switch(svc_number) {
	case ADD:
		*msp = arg1 + arg2;
		break;
	case SUB:
		*msp = arg1 - arg2;
		break;
	case MUL:
		*msp = arg1 * arg2;
		break;
	case DIV:
		*msp = arg1 / arg2;
		break;
	}
}
